export const PAGE_KEY = "page"
export const PAGE_SIZE_KEY = "page_size"
export const SEARCH_KEY = "search"
export const SEARCH_WITH_ENTER_KEY = "q"
export const UZS_SIGN = "UZS"
export const USD_SIGN = "USD"
